module.exports = {
  allowCypressEnv: false,
  experimentalWebKitSupport: true,
  experimentalFastVisibility: false,
  experimentalMemoryManagement: true,
  projectId: 'i8w349',
  video: 'chrome',
  videoCompression: 15,
  viewportWidth: 1200,
  viewportHeight: 800,
  chromeWebSecurity: false,
  defaultCommandTimeout: 10000,
  taskTimeout: 30000,
  launchTimeout: 300000,
  experimentalFetchPolyfill: true,
  requestTimeout: 45000,
  responseTimeout: 45000,
  pageLoadTimeout: 90000,
  numTestsKeptInMemory: 10,
  downloadsFolder: 'cypress/results/downloads',
  watchForFileChanges: false,
  reporter: 'junit',
  reporterOptions: {
    mochaFile: 'results/test-results-[hash].xml',
    toConsole: true,
    includePending: true,
  },
  env: {
    SALES_FORCE_SUBDOMAIN: 'mcks7qzd02s8n5pw75qbbjpkksxq',
    SALES_FORCE_CLIENT_ID: 'q5m91s1ymx1dvbjoi9nma0sb',
    SALES_FORCE_CLIENT_SECRET: 'DO NOT COMMIT THIS',
    SALES_FORCE_ACCOUNT_ID: '515008042',
    BROWSERSTACK_LOCAL: false,
  },
  e2e: {
    specPattern: 'cypress/integration/**/*.spec.ts',
    testIsolation: true,
    baseUrl: 'https://www.example.com',
    experimentalRunAllSpecs: true,
  },
};
